{
 "title": "SLO Burn Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Estimated Total Events in SLO Period",
   "type": "graph",
   "description": "Based on current rate of events, compute the total number of events we'll expect to see over the total SLO period",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "expected_events{job=\"lb\"}"
    }
   ]
  },
  {
   "title": "Cumulative Errors",
   "type": "graph",
   "description": "Shows just the errors being served as an example of how the slope of this line impacts the burn rate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (code)(errors{job=\"lb\"})"
    }
   ]
  },
  {
   "title": "Burn Rate vs Threshold",
   "type": "graph",
   "description": "shows the current rate of consumption of errors (burn rate) vresus the computed threshold that would fire an alert (based on the current total expected events within SLO period)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slo_burn_rate{job=\"lb\"}"
    },
    {
     "expr": "alert_threshold{job=\"lb\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"SLOBurnRateExceeded\",alertstate=\"firing\"}"
    }
   ]
  }
 ]
}